#!/bin/bash -xe

mkdir /controller-libs
for file in $(ldd controller | grep -P -o '/[^ ]+/[^ :]+' | sort | uniq); do
  cp $file /controller-libs
done
for file in $(ldd /usr/bin/propman | grep -P -o '/[^ ]+/[^ :]+' | sort | uniq); do
  cp $file /controller-libs
done
